### ISSUE TITLE
Installation of GitHub dependencies fails

### ISSUE THREAD

**Issue by mrustl** [r-universe-org/bugs#71]
Hi @jeroen,

I recently added all public R package repos of our organisation to [r-universe/kwb-r](https://github.com/r-universe/kwb-r), but installation fails for many packages relying on `Remotes` on GitHub, e.g. for [kwb.db](https://github.com/kwb-r/kwb.db) which has the following GitHub dependencies:

```
Remotes: 
    github::cran/RODBC@1.3-16,
    github::hsonne/odbc32@r3.0.0,
    github::kwb-r/kwb.datetime,
    github::kwb-r/kwb.utils
```

The r-universe GitHub Action workflow (https://github.com/r-universe/kwb-r/runs/3008665940?check_suite_focus=true#step:3:223 
) fails with: 

```
 Error : Failed to install 'RODBC' from GitHub:
    HTTP error 404.
    Not Found
  
    Did you spell the repo owner (`github::cran`) and repo name (`RODBC`) correctly?
    - If spelling is correct, check that you have the required permissions to access the repo.
  In addition: Warning message:
  packages ‘kwb.datetime’, ‘odbc32’ are not available for this version of R
  
  Versions of these packages for your version of R might be available elsewhere,
  see the ideas at
  https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
````

However the Rcmdcheck workflow in our KWB-R organisation works perfectly: 
https://github.com/KWB-R/kwb.db/actions/workflows/R-CMD-check.yaml 

Any idea how this can be fixed?

**Comment by jeroen** [comment]
R-universe does not use the remotes field in packages when building. This is because users should be able to use `install.packages("yourpkg")`, which requires that the dependencies are either in the same CRANlike repo, or on CRAN.

The r-universe way is to not use a remotes field, but instead simply include the non-cran dependencies in your registry. That way they get included in your package repository, and it becomes consistent.

But because many people use the remotes field, our system automatically includes packages listed in "remotes" in your universe, as you can see on the dashboard. https://kwb-r.r-universe.dev/ui#builds. However in the first build, it can lead to a race condition, a package is checked before all it's "remote" dependencies are  built and deployed in your CRANlike repo.

I haven't found a good solution, but you can easily fix it by triggering a new build (using a commit to the package) once all of it's dependencies have become available in your universe repo. I'll also try to trigger a few rebuilds for you.

**Comment by mrustl** [comment]
Thanks for the explaination and your effort for manually triggering new builds. 

Just wondering about several errors occuring during `Deploy to package server`: 
*   R package [ropencilabs/travis](https://github.com/ropencilabs/travis): `curl: (55) OpenSSL SSL_write: Broken pipe, errno 32` (see: https://github.com/r-universe/kwb-r/runs/3011229822?check_suite_focus=true#step:4:555)
*  R package [UptakeOpenSource/pkgnet](https://github.com/UptakeOpenSource/pkgnet): `curl: (52) Empty reply from server` ( see: https://github.com/r-universe/kwb-r/runs/3010886662?check_suite_focus=true#step:4:477)

**Comment by jeroen** [comment]
Yes I'm debugging the deploy errors as we speak, I think my datacenter is having some issues :/

**Comment by jeroen** [comment]
OK I think the problems are fixed and your packages should be there now.

By the way, maybe you should revise if you still need all those `remote` dependencies. Some of them seem available form CRAN as well.

**Comment by mrustl** [comment]
> OK I think the problems are fixed and your packages should be there now.

Many thanks....currently I try to trigger rebuilds for four remaining R packages still missing on r-universe (by commiting to them on GitHub).  Do you have already plans how this could be simplified in the future (e.g. by enabling the repo-owner also to restart the GH actions jobs?). 
 
> By the way, maybe you should revise if you still need all those `remote` dependencies. Some of them seem available form CRAN as well.

Thanks for the hint and may be we can get rid of a few (if I would have the time to check out). However, the problem with relying on `Remotes` is that some of the CRAN packages (e.g. [swmmr](https://github.com/dleutnant/swmmr)) are not well maintained anymore - as mentioned in your talk [Monitoring health and impact of open-source projects](https://resources.rstudio.com/resources/rstudioglobal-2021/monitoring-health-and-impact-of-open-source-projects/) - and issues are open for months, so we (or better my colleague @hsonne) decided to take over and make these fixes....
